 export var currentPage ="home"
 
 export const homeInfo = {
    "Introduction":
   "Agval Networks(Pty) is a company registered in Botswana which is operating to serve stakeholders in agriculture value chain",
    "Vision":"At AgVal Networks, we envision a future where the agricultural value chain in Africa and beyond operates with maximum efficiency, sustainability, and profitability. Our ultimate goal is to foster robust growth and development in the agricultural industry, and by extension, accelerate the economic upliftment of the people of Africa and the world. We strive to broaden our impact by extending our services, first throughout southern Africa, then across the entire continent, and eventually on a global scale.",
 
    "Mission":
    [{"paragraph":"AgVal Networks is dedicated to strengthening the links in the agricultural value chain by providing comprehensive solutions tailored to our stakeholders' unique needs. We leverage technology and our extensive industry knowledge to develop innovative tools and services that address critical unmet needs, from meteorological data management to market discovery for farmers."},
    {"paragraph":"Our mission encompasses these three core elements:"},
 
    {"paragraph":{"keyPoint":"Enhancing Meteorological Data Management:","explanation": "We aim to improve meteorological data management, processing, tailoring, and dissemination for National Meteorological and Hydrological Services (NMHSs) in Africa. To this end, we are committed to creating cutting-edge tools and online platforms that allow NMHSs to process and serve their data more efficiently and effectively."}},

    {"paragraph":{"keyPoint":"Improving Agronomic Data Dissemination and Application:","explanation": "We are focused on enhancing the dissemination and application of agrometeorological and agronomic data for farmers across Africa. By developing user-friendly online tools, we make it possible for farmers to access automated data and receive timely advisories, thus enabling them to make informed decisions that boost their productivity and profitability."}},

    {"paragraph":{"keyPoint":"Facilitating Market Discovery for Farmers:","explanation": "We are dedicated to expanding market access for farmers in Africa. We are in the process of developing a two-sided online marketplace where farmers can register their farm produce, and buyers can easily discover and purchase these goods online. By bridging this gap, we aim to promote fair trade and ensure farmers receive the best value for their produce."}},
    {"paragraph":"Through our Climate Services division, ClimApp Technologies, we further aim to provide crucial climate services to users in the agricultural value chain. Our focus is on developing and providing instrumentation that supports climate services and stakeholders involved in the cold supply chain."},

    {"paragraph":"As we continue to expand our services and impact, our underlying aim remains the same: to create robust business solutions that bolster the agricultural industry and contribute to the economic growth and upliftment of Africa's people."}
 ]
 }

export const aboutInfo ={
<<<<<<< HEAD
    "about":[{"paragraph":"AgVal Networks (PTY) LTD is (aims to be) a leading provider of services that strengthen links in the agricultural value chain, through the provision of equipment, information products, online and software tools, and consultancy services to stakeholders in the agricultural value chain, from the farmer, through value added processing, logistics, consumers and policy makers. Emphasis is being given to the development of strategic information transmission services that can add value to stakeholders."},
             {"paragraph":"Through its Climate Services division, ClimApp Technologies (which will also have its own website), AgVal Networks strives to provide climate services to users in the agricultural value chain such as farmers. We are further expanding to provide instrumentation to support climate services, such as weather stations, as well as instrumentation to support stakeholders who serve the cold supply chain."},
            {"paragraph":" The ultimate underlying aim of AgVal Networks is tied to the ethos of its founding director which is to accelerate Africa's economic growth and upliftment of its people by creating robust business solutions that support the agricultural industry. AgVal Networks was registered as a Proprietary Limited company in Botswana in 2021 (2 years ago). ClimApp Technologies is a registered trading name T/A (Trading As). AgVal has offices in Gaborone."},{
                "paragraph":"Our long term vision is to be operating in southern Africa, then Africa, and eventually global. We also have a similarly named company Registered in Zimbabwe.AgVal has identified three largely unmet needs in our target martket that we believe we can help to solve. One of these is meteorological data management, processing, tailoring and dissemination for NMHSs in Africa."
            },{"paragraph":"To solve this, we plan to develop tools and online platforms that NMHSs can use to process and serve their data. Another is agrometeorological and agronomic data dissemination and application for farmers in Africa. To solve this, we are developing online tools where farmers can log in and get automated data and advisory. A third is market discovery for farmers in Africa, so that farmers can expand their market access by having buyers reach them directly. To solve this, we are developing a two-sided market where farmers can register their farm produce, and buyers can find and buy the goods online."}]
}

=======
    "companyHistory":"Founded in 2021, AgVal Networks (PTY) LTD has quickly emerged as a leading provider of services that strengthen the agricultural value chain. Our approach emphasizes the development of strategic information transmission services that add value to all stakeholders, from farmers to policy makers. With a strong presence in Botswana, our mission is to accelerate Africa's economic growth and upliftment of its people by supporting the agricultural industry.",
    "directorMessage":{"message":"I am proud to lead AgVal Networks in our pursuit to innovate and enhance the agricultural value chain. With our focus on meteorological data management, agrometeorological data dissemination, and market discovery for farmers, we are committed to addressing the under-served needs in our target market. Our journey is guided by the ethos of creating robust business solutions that not only support the industry but also contribute to the larger goal of uplifting the people of Africa. Together, we shall reach new heights.","director": "– Dr. Tamuka Magadzire"},
     "botswana":"AgVal Networks has a strong footprint in Botswana. Our headquarters in Gaborone serve as the hub for our extensive operations, and our registered entity in Zimbabwe reflects our commitment to expanding our reach. We have identified three core unmet needs in our market and have initiated strategies to address them through innovative tools and platforms. Our short-term plans include developing various platforms and tools for farmers, governments, and other stakeholders in the agricultural value chain.",
    "climApp":"Our Climate Services division, ClimApp Technologies, specializes in providing climate services to users in the agricultural value chain, such as farmers. This includes expanding to provide instrumentation to support climate services like weather stations, as well as support for stakeholders in the cold supply chain. ClimApp Technologies has its dedicated focus and is developing its own website to cater to specialized needs in climate services.",
    "offices":{"Gaborone":"Plot 131 Independence Avenue, Kohinoor Office Park – Unit 7B, Gaborone ,Botswana, Tel: +267-7524-8833"}
}
>>>>>>> 3390bd3 (theme interchangibility and About Us Page)
